server:
  port: 8080
  servlet.context-path: /api

spring:
  profiles.active: dev
  application.name: ExamenTecso
      
---
#DEV CONFIGURATION
spring:
  profiles: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver: org.h2.Driver
    username: sa

---        
#PROD CONFIGURATION
spring:
  profiles: qa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver: org.h2.Driver
    username: sa